// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineEnrollment.Data;

#nullable disable

namespace OnlineEnrollment.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328154745_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineEnrollment.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@onlineenrollment.com",
                            FullName = "Administrator",
                            Password = "admin123"
                        });
                });

            modelBuilder.Entity("OnlineEnrollment.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EnrolledCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Slots")
                        .HasColumnType("int");

                    b.Property<int>("Units")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "BSA",
                            Department = "Business",
                            EnrolledCount = 0,
                            IsActive = true,
                            Name = "BS Accountancy",
                            Schedule = "MWF 7:30-9:00",
                            Slots = 40,
                            Units = 24
                        },
                        new
                        {
                            Id = 2,
                            Code = "BSBA",
                            Department = "Business",
                            EnrolledCount = 0,
                            IsActive = true,
                            Name = "BS Business Administration",
                            Schedule = "TTH 7:30-9:00",
                            Slots = 40,
                            Units = 24
                        },
                        new
                        {
                            Id = 3,
                            Code = "BSE",
                            Department = "Business",
                            EnrolledCount = 0,
                            IsActive = true,
                            Name = "BS Entrepreneurship",
                            Schedule = "MWF 9:00-10:30",
                            Slots = 40,
                            Units = 24
                        },
                        new
                        {
                            Id = 4,
                            Code = "BSME",
                            Department = "Business",
                            EnrolledCount = 0,
                            IsActive = true,
                            Name = "BS Management Engineering",
                            Schedule = "TTH 9:00-10:30",
                            Slots = 40,
                            Units = 24
                        },
                        new
                        {
                            Id = 5,
                            Code = "BSCS",
                            Department = "STEM",
                            EnrolledCount = 0,
                            IsActive = true,
                            Name = "BS Computer Science",
                            Schedule = "MWF 7:30-9:00",
                            Slots = 40,
                            Units = 24
                        },
                        new
                        {
                            Id = 6,
                            Code = "BSIT",
                            Department = "STEM",
                            EnrolledCount = 0,
                            IsActive = true,
                            Name = "BS Information Technology",
                            Schedule = "TTH 7:30-9:00",
                            Slots = 40,
                            Units = 24
                        },
                        new
                        {
                            Id = 7,
                            Code = "BSCE",
                            Department = "STEM",
                            EnrolledCount = 0,
                            IsActive = true,
                            Name = "BS Civil Engineering",
                            Schedule = "MWF 9:00-10:30",
                            Slots = 40,
                            Units = 24
                        },
                        new
                        {
                            Id = 8,
                            Code = "BSEE",
                            Department = "STEM",
                            EnrolledCount = 0,
                            IsActive = true,
                            Name = "BS Electrical Engineering",
                            Schedule = "TTH 9:00-10:30",
                            Slots = 40,
                            Units = 24
                        },
                        new
                        {
                            Id = 9,
                            Code = "BSBIO",
                            Department = "STEM",
                            EnrolledCount = 0,
                            IsActive = true,
                            Name = "BS Biology",
                            Schedule = "MWF 10:30-12:00",
                            Slots = 40,
                            Units = 24
                        },
                        new
                        {
                            Id = 10,
                            Code = "BSN",
                            Department = "STEM",
                            EnrolledCount = 0,
                            IsActive = true,
                            Name = "BS Nursing",
                            Schedule = "TTH 10:30-12:00",
                            Slots = 40,
                            Units = 24
                        },
                        new
                        {
                            Id = 11,
                            Code = "BSPSY",
                            Department = "Social Sciences",
                            EnrolledCount = 0,
                            IsActive = true,
                            Name = "BS Psychology",
                            Schedule = "MWF 7:30-9:00",
                            Slots = 40,
                            Units = 24
                        },
                        new
                        {
                            Id = 12,
                            Code = "ABCOM",
                            Department = "Social Sciences",
                            EnrolledCount = 0,
                            IsActive = true,
                            Name = "AB Communication",
                            Schedule = "TTH 7:30-9:00",
                            Slots = 40,
                            Units = 24
                        },
                        new
                        {
                            Id = 13,
                            Code = "ABPOLSCI",
                            Department = "Social Sciences",
                            EnrolledCount = 0,
                            IsActive = true,
                            Name = "AB Political Science",
                            Schedule = "MWF 9:00-10:30",
                            Slots = 40,
                            Units = 24
                        },
                        new
                        {
                            Id = 14,
                            Code = "ABFA",
                            Department = "Social Sciences",
                            EnrolledCount = 0,
                            IsActive = true,
                            Name = "AB Fine Arts",
                            Schedule = "TTH 9:00-10:30",
                            Slots = 40,
                            Units = 24
                        },
                        new
                        {
                            Id = 15,
                            Code = "BSED",
                            Department = "Education",
                            EnrolledCount = 0,
                            IsActive = true,
                            Name = "BS Secondary Education",
                            Schedule = "MWF 7:30-9:00",
                            Slots = 40,
                            Units = 24
                        },
                        new
                        {
                            Id = 16,
                            Code = "BEED",
                            Department = "Education",
                            EnrolledCount = 0,
                            IsActive = true,
                            Name = "BS Elementary Education",
                            Schedule = "TTH 7:30-9:00",
                            Slots = 40,
                            Units = 24
                        },
                        new
                        {
                            Id = 17,
                            Code = "BSARCH",
                            Department = "Education",
                            EnrolledCount = 0,
                            IsActive = true,
                            Name = "BS Architecture",
                            Schedule = "MWF 9:00-10:30",
                            Slots = 40,
                            Units = 24
                        },
                        new
                        {
                            Id = 18,
                            Code = "MMA",
                            Department = "Education",
                            EnrolledCount = 0,
                            IsActive = true,
                            Name = "Multimedia Arts",
                            Schedule = "TTH 9:00-10:30",
                            Slots = 40,
                            Units = 24
                        },
                        new
                        {
                            Id = 19,
                            Code = "HRM",
                            Department = "General Education",
                            EnrolledCount = 0,
                            IsActive = true,
                            Name = "Hotel & Restaurant Management",
                            Schedule = "MWF 7:30-9:00",
                            Slots = 40,
                            Units = 24
                        },
                        new
                        {
                            Id = 20,
                            Code = "BSLM",
                            Department = "General Education",
                            EnrolledCount = 0,
                            IsActive = true,
                            Name = "BS Legal Management",
                            Schedule = "TTH 7:30-9:00",
                            Slots = 40,
                            Units = 24
                        });
                });

            modelBuilder.Entity("OnlineEnrollment.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("OnlineEnrollment.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("OnlineEnrollment.Models.Enrollment", b =>
                {
                    b.HasOne("OnlineEnrollment.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineEnrollment.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OnlineEnrollment.Models.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("OnlineEnrollment.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
